databases:
  - name: Anki_Clone
    databaseName: anki_clone_db
    user: armantark

services:
  - type: web
    name: Anki_Clone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Anki_Clone.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Anki_Clone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4