# Generated by Django 4.2.1 on 2023-05-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('bin', models.PositiveIntegerField(default=0)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
