name: Python application test with Django

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: Anki_Clone.settings
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
